# docker build -f Dockerfile_optical_flow -t jacobloe/optical_flow:0.1 .
FROM python:3.8

ENV DEBIAN_FRONTEND noninteractive

COPY requirements_optical_flow.txt /root

RUN pip3 install --trusted-host pypi.python.org -r /root/requirements_optical_flow.txt
RUN apt-get update && apt-get install -y vim

COPY optical_flow.py /root

VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "optical_flow.py"]
